### PR TITLE
Small fixes to XDS <> FHIR metadata mappers

### LINKED ISSUE #14: Small fixes to XDS <> FHIR metadata mappers
1. XON <> Organization. XON can have an identifier without assigning authority if it is an OID.

It is common for organizations to be uniquely identified by an OID. In
such cases, the Organization (Identifier component 10) may contain the
organization’s OID. If the Organization Identifier is not an OID, the
metadata use assumes that it has been assigned so that the composite Id
created by combining components 6 and 10 is a unique identifier for the
organization.

2. XCN <> Practitioner. The code expects an assigning authority for the identifier. But either the name or the identifier is expected. So in case of a name-only XCN, the identifier does not need to be mapped. The rules for XCN are:

Either name or an identifier shall be present. Inclusion of other
components is optional provided the slot value length restrictions imposed
by ebXML3.0, 256 characters, is not exceeded.

If component 1 (Id Number) is specified, component 9 (Assigning
Authority) shall be present if available.

3. Assoc entryUuid might be empty on submission and then needs to be assigned by registry

### PR DESCRIPTION
**Pull request by walcovanloon**
Resolve mapping issues in #14 
 - XON <> Organization. XON can have an identifier without assigning authority if it is an OID.
 - XCN <> Practitioner. The code expects an assigning authority for the identifier. But either the name or the identifier is expected. So in case of a name-only XCN, the identifier does not need to be mapped. The rules for XCN are:
 - Assoc entryUuid might be empty on submission and then needs to be assigned by registry

### CODE REVIEW

**Review by Thopap — APPROVED** [review]

File: src/main/java/org/openehealth/app/xdstofhir/registry/register/RegisterDocumentsProcessor.java [hunk 1]
```diff
@@ -394,9 +394,9 @@ private void assignRegistryValues(XDSMetaClass xdsObject, List<Association> asso
      */
     private void assignRegistryValues(List<Association> associations) {
         for (var assoc : associations) {
-            if (!assoc.getEntryUuid().startsWith(MappingSupport.UUID_URN)) {
-                var previousIdentifier = assoc.getEntryUuid();
+            if (assoc.getEntryUuid() == null || !assoc.getEntryUuid().startsWith(MappingSupport.UUID_URN)) {
                 assoc.assignEntryUuid();
+                var previousIdentifier = assoc.getEntryUuid();
```
Comment (ahpatrifork) [inline src/main/java/org/openehealth/app/xdstofhir/registry/register/RegisterDocumentsProcessor.java:399]: @walcovanloon @Thopap I know this pr is merged but doesn't this introduce an error? `previousIdentifier` is initialized after assigning a new `entryUuid`, so you end up not replacing the associations's source and target uuids

Comment (Thopap) [reply src/main/java/org/openehealth/app/xdstofhir/registry/register/RegisterDocumentsProcessor.java:399]: Hi @ahpatrifork,

thank you for this review. You are right, this issue will cause that that the SS-HM associatin (as described in 4.2.2.1.5) might not be reflected correctly in the fhir request.
